[package]
name = "insight_derive"
version = "0.1.0"
authors = ["Walter Pearce <jaynus@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = "0.4"
syn = { version = "0.15" }
quote = "0.6"

[lib]
proc-macro = true